discord:
  token: "YOUR_BOT_TOKEN_HERE"
  channel-id: "YOUR_CHANNEL_ID_HERE"
  delete-non-commands: true

link:
  reward-command: "lp user {player} parent set vip"
  code-expire-minutes: 10

settings:
  debug: false
